### ISSUE TITLE
Update to Noir v0.31.0

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/tiny-noirjs-app#6]
```[tasklist]
### Prerequisites
- [ ] https://github.com/noir-lang/noir/pull/5072
- [ ] https://github.com/noir-lang/noir/pull/5166
```

Following PR https://github.com/noir-lang/noir/pull/5072, proving and verification workflow would no longer rely on NoirJS but proving backends' JS packages (e.g. bb.js) instead.

The PR also included updates to the https://noir-lang.org/docs/tutorials/noirjs_app/ doc page, but not this repo.

As this repo is linked and used as the basis of that doc page, we should update this synchronously update the doc page in one go if applicable.

**Comment by critesjosh** [comment]
This should go along with updating the [corresponding docs page](https://noir-lang.org/docs/tutorials/noirjs_app)
